version: '3.8'
services:
  test_db:
    build: .
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sqlp_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
